services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "9090:9090"  # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
    networks:
      - salesops-net
      
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_SERVER_JSON_FILE: /pgadmin/connections.json
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - ./pgadmin:/pgadmin
    networks:
      - salesops-net
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.localhost`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.routers.admin.service=admin-service"
      - "traefik.http.services.admin-service.loadbalancer.server.port=80"
  

      
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: salesops
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - salesops-net
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=${API_ENDPOINT}
      - VITE_WS_URL=${WS_ENDPOINT}
    depends_on:
      - backend
    networks:
      - salesops-net
    container_name: salesops-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.service=frontend-service"
      - "traefik.http.services.frontend-service.loadbalancer.server.port=5173"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      # Hot deploy — drop WARs here and WildFly picks them up automatically
      - ./backend/target/sales-ops-1.0.war:/opt/jboss/wildfly/standalone/deployments/sales-ops.war  
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - salesops-net
    container_name: salesops-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.service=backend-service"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8080"
      
  #backend:
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile.dev
  #  environment:
  #    - SPRING_PROFILES_ACTIVE=dev
  #  volumes:
  #   - ./backend/target/classes:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes
  #    - ./backend/target/dependency:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib
  #    - ./backend/context.xml:/usr/local/tomcat/conf/context.xml
  #  depends_on:
  #    db:
  #      condition: service_healthy
  #  restart: unless-stopped
  #  networks:
  #    - salesops-net
  #  container_name: salesops-backend
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.backend.rule=Host(`api.localhost`)"
  #    - "traefik.http.routers.backend.entrypoints=web"
  #    - "traefik.http.routers.backend.service=backend-service"
  #    - "traefik.http.services.backend-service.loadbalancer.server.port=8080"

volumes:
  pg_data:

networks:
  salesops-net:
    driver: bridge
