<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">


	<modelVersion>4.0.0</modelVersion>
	<groupId>br.edu.ufrgs</groupId>
	<artifactId>sales-ops</artifactId>
	<version>1.0</version>
	<packaging>war</packaging>


	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<spring-boot.version>4.0.6</spring-boot.version>
		<maven.build.cache.enabled>true</maven.build.cache.enabled>
	</properties>


	<dependencies>
		<!-- Web starter -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<!-- Jakarta Servlet -->
		<dependency>
			<groupId>jakarta.servlet</groupId>
			<artifactId>jakarta.servlet-api</artifactId>
			<version>6.0.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>


	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
    
	<profiles>
		<!-- DEVELOPMENT PROFILE -->
		<profile>
		    	<id>dev</id>
		    	<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			
			<dependencies>
				<dependency>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-devtools</artifactId>
					<optional>true</optional>
				</dependency>

				<!-- Hot reload (DevTools) -->
				<dependency>
				    <groupId>org.springframework.boot</groupId>
				    <artifactId>spring-boot-devtools</artifactId>
				    <optional>true</optional>
				</dependency>
			</dependencies>
			
			<build>
				<plugins>
					<!-- Spring Boot plugin -->
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<version>${spring-boot.version}</version>
						<configuration>
							<mainClass>br.edu.ufrgs.Application</mainClass>
							<packaging>war</packaging>
						</configuration>
					</plugin>

					<!-- WAR compiler -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.13.0</version>
						<configuration>
							<release>17</release>
							<incremental>true</incremental>
						</configuration>
					</plugin>

					<!-- War plugin optimization -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<version>3.4.0</version>
						<configuration>
							<failOnMissingWebXml>false</failOnMissingWebXml>
							<packagingExcludes>WEB-INF/lib/*.jar</packagingExcludes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		
		<!-- PRODUCTION PROFILE -->
		<profile>
			<id>prod</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
						<version>${spring-boot.version}</version>
						<configuration>
							<mainClass>br.edu.ufrgs.Application</mainClass>
							<packaging>war</packaging>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
