<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">


	<modelVersion>4.0.0</modelVersion>
	<groupId>br.edu.ufrgs</groupId>
	<artifactId>sales-ops</artifactId>
	<version>1.0</version>
	<packaging>war</packaging>


	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<maven.build.cache.enabled>true</maven.build.cache.enabled>
  		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  		<jakarta.ee.version>10.0.0</jakarta.ee.version>
	</properties>


	<dependencies>
		<!-- Jakarta EE 10 (Servlet + WebSocket) -->
		<dependency>
			<groupId>jakarta.platform</groupId>
			<artifactId>jakarta.jakartaee-api</artifactId>
			<version>${jakarta.ee.version}</version>
			<scope>provided</scope>
		</dependency>

		<!-- junit 5 (jupiter) -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.10.2</version>
			<scope>test</scope>
		</dependency>
	</dependencies>


	<dependencyManagement>
		<dependencies>
		</dependencies>
	</dependencyManagement>
    
	<profiles>
		<!-- DEVELOPMENT PROFILE -->
		<profile>
		    	<id>dev</id>
		    	<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
						
			<build>
				<plugins>
					<!-- WAR compiler -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.13.0</version>
						<configuration>
							<compilerArgs>
								<arg>-parameters</arg>
							</compilerArgs>
							<release>17</release>
							<incremental>true</incremental>
						</configuration>
					</plugin>

					<!-- plugin do maven surefire (obrigatório para rodar junit 5 no maven) -->
		    			<plugin>
			      			<groupId>org.apache.maven.plugins</groupId>
			      			<artifactId>maven-surefire-plugin</artifactId>
			      			<version>3.2.5</version>
		    			</plugin>

		    			<!-- plugin do jacoco -->
		    			<plugin>
			      			<groupId>org.jacoco</groupId>
			      			<artifactId>jacoco-maven-plugin</artifactId>
			      			<version>0.8.11</version>
			      			<executions>
							<!-- inicializa o agente do jacoco antes dos testes rodarem -->
							<execution>
					  			<id>prepare-agent</id>
					  			<goals>
					    				<goal>prepare-agent</goal>
					  			</goals>
							</execution>
							<!-- gera o relatório HTML após a execução dos testes -->
							<execution>
					  			<id>report</id>
					  			<phase>test</phase>
					  			<goals>
					    				<goal>report</goal>
					  			</goals>
							</execution>
			      			</executions>
		    			</plugin>

					<!-- War plugin optimization -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-war-plugin</artifactId>
						<version>3.4.0</version>
						<configuration>
							<failOnMissingWebXml>false</failOnMissingWebXml>
							<packagingExcludes>WEB-INF/lib/*.jar</packagingExcludes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		
		<!-- PRODUCTION PROFILE -->
		<profile>
			<id>prod</id>
			<build>
				<plugins>
				
					<!-- WAR compiler -->
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>3.13.0</version>
						<configuration>
							<compilerArgs>
								<arg>-parameters</arg>
							</compilerArgs>
							<release>17</release>
							<incremental>true</incremental>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>
</project>
