default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= ENV.fetch("DB_HOST", "localhost") %>
  port:     <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USER", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: salesops_development

test:
  <<: *default
  database: salesops_test

production:
  <<: *default
  database: salesops_production
